---
title: "Syllabus"
author: "Ed Hagen"
date: "2025-08"
---

```{r setup, include=FALSE}
seq.Date(as.Date("2025-08-18"),as.Date("2025-12-05"), by="7 days")
```

* Instructor: Ed Hagen
* Email: <edhagen@wsu.edu>
* Office hours: Anytime. Email for Zoom appointment
<!-- * Course website: <http://anthro.vancouver.wsu.edu/faculty/hagen> -->
* Lecture hall: VMMC 219 and live over Zoom
* Days and times: MW 10:35-11:50
* Semester: Fall 2025
* Credits: 3

## Course description

This course introduces an evolutionary biological approach to human psychology and behavior. Topics that will be explored include the modern synthesis, human sexuality, male-female relations, cooperation, violence, parent-child relations, mental illnesses, and cultural transmission. For the complete list of topics, assignments, and grading, see below.

## Textbooks and readings

* Evolutionary Psychology: The New Science of the Mind, latest edition. David Buss.

* The Selfish Gene, 2nd edition or later. Richard Dawkins.

* Selected readings available from the course web site.

## Grading

Students are responsible for all material in the lectures and the assigned portions of the texts. Grading will be on a curve, and will be based on three tests:

* Two midterms (each with 25 multiple choice & true/false questions): 25% of grade each
* Final (50 multiple choice & true/false questions): 50% of grade

You are responsible for assigned reading even when the material is not covered in lecture. The final exam is comprehensive (i.e., it covers material from the entire course).

## Assigned reading and test dates

**EXAMS CANNOT BE RESCHEDULED ON AN INDIVIDUAL BASIS. MAKEUP EXAMS ONLY AVAILABLE FOR STUDENTS WITH A MEDICAL OR SIMILAR EXCUSE. DO NOT SCHEDULE TRIPS OR OTHERWISE PLAN TO BE ABSENT DURING THE MIDTERMS OR FINALS WEEK!**

## Week 1 (Aug 19): Adaptation and natural selection

* Buss: Ch. 1
* Dawkins: Ch. 1-4

## Week 2 (Aug 26): The modern synthesis

* Buss: Ch. 2
* Dawkins: Ch. 5

## Week 3 (Sep 2): Sex I (Long-term mating)

* Buss: Ch. 4-5

## Week 4 (Sep 9): Sex II (Short-term mating)

* Buss: Ch. 6

## Week 5 (Sept 16): Sex III (Battle of the sexes)

* Buss: Ch. 11
* Dawkins: Ch. 9

## **MIDTERM 1 EXAM: Wed, Sep 18**

The midterm consists of 25 multiple choice and true/false questions on all readings and lectures through week 5.

## Week 6 (Sep 23): Parenting

* Buss: Ch. 7
* Dawkins: Ch. 7

## Week 7 (Sep 30): Kinship

* Buss: Ch. 8
* Dawkins: Ch. 6
* Lieberman (web site)

## Week 8 (Oct 7): Reciprocal altruism

* Buss: Ch. 9

## Week 9 (Oct 14): Aggression

* Buss: Ch. 10
* Daly and Wilson (web site)

## Week 10 (Oct 21): Warfare

* Chagnon 1988. Life Histories, Blood Revenge, and Warfare in a Tribal Population (web site)

## Week 11 (Oct 28): TBA

## **MIDTERM EXAM 2: Wed, Oct 30**

The midterm consists of 25 multiple choice and true/false questions on all readings and lectures from week 6 through week 10.

## Week 12 (Nov 4): Darwinian medicine I: Drug use

* Buss: Ch. 3
* Sullivan and Hagen 2002. Psychotropic substance-seeking: evolutionary pathology or adaptation? (web site)

## Week 13 (Nov 11): Darwinian medicine II: Depression and suicide

* Buss: Ch. 3, Ch. 13 section on clinical psychology
* Hagen 1999. The functions of postpartum depression (web site)
* Hagen 2007. Gestures of despair and hope: A view on deliberate self-harm from economics and evolutionary biology (web site)

## Week 14 (Nov 18): The evolution of culture

* Buss: Ch. 13 section on cultural psychology
* Hagen and Hammerstein 2007. Did Neanderthals and other early humans sing? Seeking the biological  roots of music in the territorial advertisements of primates, lions,  hyenas, and wolves (web site)
* Sugiyama 2001. Food, foragers and folklore: the role of narrative in human subsistence (web site)
* Henrich and McElreath 2003. The evolution of cultural evolution (web site)

## **Week 15 (Nov 25): Thanksgiving**

## Week 16 (Dec 2): TBA

## **FINAL EXAM Fri Dec 13, 8-10 am**

The final consists of 50 multiple and true/false questions on material from the *entire course*.

## University learning goals

Visit this page to see how anthropology courses satisfy WSU learning goals:

http://anthro.vancouver.wsu.edu/programs/learning-goals/